before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  script:
    - bundle exec rspec
    
staging:
  type: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --api-key=$a4c03b57-1ce5-412c-bfa0-d22cf844ae05
  only:
  - master

production:
  type: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --api-key=$a4c03b57-1ce5-412c-bfa0-d22cf844ae05
  only:
  - tags