before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  script:
    - bundle exec rspec
    
staging:
  type: deploy
  script:
  - gem install dpl
  - dpl --provider=heroku --app=deploygcs --api-key=$df17f508-fe8c-4e83-8bb5-c68763b573db
  only:
  - master