# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0bb10404ff61bc84b50764b3f844df6b6893981f751488a6161d7700e6bf57c3cbe0950dd5a9af83473b1c365cafb657f46a5b822978b53f1ccd20e3873e36e
  OPEN_HUB_KEY: a8b2141ce1264ca5e99e49e1cb37dbb589949bc910cc6d71a938c8db7f51136c
  EMAIL_SMTP: smtp.gmail.com
  EMAIL: mail.flosscoach
  EMAIL_PASS: flosscoach@
  EMAIL_PORT: 587
  FACEKEY: 536873056515793
  FACETOKEN: 2c3cce29072082ed57a3d07fc9f25623
  TWITTERKEY: 1sa3tuMYEN7iUcEm3pkvNnGwm
  TWITTERTOKEN: a3SyrLVL8W4X8sA653lLSdFjssifOmlJbFMNsLGIVszlEBCsaI
  GITKEY: aed2636dcc89e690eb67
  GITTOKEN: d1215edd5f83d84f1e5c1492dfbd6b6b04c1f33a
test:
  secret_key_base: f0bb10404ff61bc84b50764b3f844df6b6893981f751488a6161d7700e6bf57c3cbe0950dd5a9af83473b1c365cafb657f46a5b822978b53f1ccd20e3873e36e
  EMAIL_SMTP: smtp.gmail.com
  EMAIL: mail.flosscoach
  EMAIL_PASS: flosscoach@
  EMAIL_PORT: 587
  FACEKEY: 536873056515793
  FACETOKEN: 2c3cce29072082ed57a3d07fc9f25623
  TWITTERKEY: 1sa3tuMYEN7iUcEm3pkvNnGwm
  TWITTERTOKEN: a3SyrLVL8W4X8sA653lLSdFjssifOmlJbFMNsLGIVszlEBCsaI
  GITKEY: aed2636dcc89e690eb67
  GITTOKEN: d1215edd5f83d84f1e5c1492dfbd6b6b04c1f33a
production:
  OPEN_HUB_KEY: a8b2141ce1264ca5e99e49e1cb37dbb589949bc910cc6d71a938c8db7f51136c
  EMAIL_SMTP: smtp.gmail.com
  EMAIL: mail.flosscoach
  EMAIL_PASS: flosscoach@
  EMAIL_PORT: 587
  FACEKEY: 536873056515793
  FACETOKEN: 2c3cce29072082ed57a3d07fc9f25623
  TWITTERKEY: 1sa3tuMYEN7iUcEm3pkvNnGwm
  TWITTERTOKEN: a3SyrLVL8W4X8sA653lLSdFjssifOmlJbFMNsLGIVszlEBCsaI
  GITKEY: aed2636dcc89e690eb67
  GITTOKEN: d1215edd5f83d84f1e5c1492dfbd6b6b04c1f33a
