open_hub: "#{ohp.description} <br>
                 <iframe src='https://www.openhub.net/p/#{ohp.vanity_url}/widgets/
                 project_factoids_stats' scrolling='no' marginheight='0' marginwidth='0'
                 style='height: 220px; width: 370px; border: none'></iframe>"
