about:
    title: "About"
    slug: "about"
    tab: "about"
    pos_x: 4
    pos_y: 0
    width: 8
    height: 5
    content: "Fill with text"

links:
    title: "Links"
    slug: "links"
    tab: "about"
    pos_x: 0
    pos_y: 0
    width: 4
    height: 3
    content: "Fill with text"

technical_skills:
    title: "Technical Skills"
    slug: "technical_skills"
    tab: "how_to_start"
    pos_x: 0
    pos_y: 0
    width: 6
    height: 4
    content: "Fill with text"

soft_skills:
    title: "Soft skills required"
    slug: "soft_skills"
    tab: "how_to_start"
    pos_x: 6
    pos_y: 0
    width: 6
    height: 4
    content: "Fill with text"

basic_contribution_flow:
    title: "Basic contribution flow to follow"
    slug: "basic_contribution_flow"
    tab: "how_to_start"
    pos_x: 0
    pos_y: 4
    width: 12
    height: 7
    content: |
                <div class="steps steps-vertical">
                  <div class="step done">
                    <span class="step-number">1</span>
                    <div class="step-desc">
                      <span class="step-title">Learn about the project and skills</span>
                      <p>First you need to learn about the project. Search on it and see if it really interests you propose.</p>
                    </div>
                  </div>
                  <div class="step done">
                    <span class="step-number">2</span>
                    <div class="step-desc">
                      <span class="step-title">Setup you local workspace</span>
                      <p>Install the development environment on your machine.</p>
                    </div>
                  </div>
                  <div class="step done">
                    <span class="step-number">3</span>
                    <div class="step-desc">
                      <span class="step-title">Find a task to start with</span>
                      <p>Search a task for beginners to start contributing</p>
                    </div>
                  </div>
                  <div class="step done">
                    <span class="step-number">4</span>
                    <div class="step-desc">
                      <span class="step-title">Study and change the code</span>
                      <p>Dont forget to test your code!</p>
                    </div>
                  </div>
                  <div class="step done">
                    <span class="step-number">5</span>
                    <div class="step-desc">
                      <span class="step-title">Submit your contribution</span>
                      <p>Congratulations, you have successfully contributed to the project.</p>
                    </div>
                  </div>
                  <div class="step error">
                    <div class="step-desc text-center">
                      <span class="step-title text-center">Have a question?</span>
                      <p>Get support from the community.</p>
                    </div>
                  </div>
                </div>

workspace_setup:
    title: "Workspace setup"
    slug: "workspace_setup"
    tab: "configure_workspace"
    pos_x: 0
    pos_y: 0
    width: 5
    height: 4
    content: "Fill with text"

resources_provided:
    title: "Resources provided by project"
    slug: "resources_provided"
    tab: "configure_workspace"
    pos_x: 5
    pos_y: 0
    width: 7
    height: 5
    content: "Fill with text"

code_documentation:
    title: "Code documentation"
    slug: "code_documentation"
    tab: "know_the_code"
    pos_x: 0
    pos_y: 0
    width: 5
    height: 4
    content: "Fill with text"

searcheable_resources:
    title: "Searcheable resources"
    slug: "searcheable_resources"
    tab: "know_the_code"
    pos_x: 5
    pos_y: 0
    width: 5
    height: 4
    content: "Fill with text"

send_contribution:
    title: "Submitting yout contribution"
    slug: "send_contribution"
    tab: "know_the_code "
    pos_x: 5
    pos_y: 0
    width: 5
    height: 4
    content: "Fill with text"

open_hub_about:
    title: "About"
    slug: "about"
    tab: "about"
    pos_x: 4
    pos_y: 0
    width: 8
    height: 5
    content: "#{ohp.description} <br>
               <iframe src='https://www.openhub.net/p/#{ohp.vanity_url}/widgets/
               project_factoids_stats' scrolling='no' marginheight='0' marginwidth='0'
               style='height: 220px; width: 370px; border: none'></iframe>"

open_hub_links:
    title: "Links"
    slug: "links"
    tab: "about"
    pos_x: 0
    pos_y: 0
    width: 4
    height: 3
    content: "OpenHub URL: <a href='#{ohp.html_url}'>#{ohp.html_url}</a><br>
              Homepage Url: <a href='#{ohp.homepage_url}'>#{ohp.homepage_url}</a><br>
              Download URL: <a href='#{ohp.download_url}'>#{ohp.download_url}</a>"
